name: Build del proyecto

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Clonamos el repositorio
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Configuramos Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.5.0

      # Instalamos dependencias del proyecto Discord-Clone
      - name: Install Dependencies of Discord-Clone
        run: npm install
        
      # Build del proyecto
      - name: Build Project
        run: npm run build
