name: Build del proyecto

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Clonamos el repositorio
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Configuramos Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # Instalamos dependencias del proyecto Discord-Clone
      - name: Install Dependencies of Discord-Clone
        run: npm install
        
      # Build del proyecto
      - name: Build Project
        run: npm run build
        
      - name: Check pipeline status
        run: |
          if [ "${{ job.status }}" == "cancelled" ]; then
            echo "Pipeline fue cancelada, revertir el commit"
            
            # Revertir el último commit en la rama main
            git revert --no-edit HEAD
            git push origin main
          fi
